version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword 
    depends_on:
      - ollama
    
  ollama:
    container_name: ollama
    pull_policy: always
    build:
      context: ./ollama
    ports:
      - "11434:11434"
    restart: always

  minio:
      image: minio/minio
      container_name: minio
      ports:
        - "9000:9000"
        - "9001:9001"
      volumes:
        - ./data:/data
      environment:
        MINIO_ROOT_USER: minioadmin
        MINIO_ROOT_PASSWORD: minioadmin
      command: server /data --console-address ":9001"
